//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog
    {
        public string maBlog { get; set; }
        public string maDD { get; set; }
        public string username { get; set; }
        public string content { get; set; }
        public string pic { get; set; }
        public string note { get; set; }
    
        public virtual TourDestination TourDestination { get; set; }
    }
}
