//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElecBill
    {
        public ElecBill()
        {
            this.DSDatXes = new HashSet<DSDatXe>();
            this.DSKSCanTTs = new HashSet<DSKSCanTT>();
            this.DSTourCanTTs = new HashSet<DSTourCanTT>();
        }
    
        public string maHD { get; set; }
        public string username { get; set; }
        public Nullable<double> tongTien { get; set; }
        public string paymentMethod { get; set; }
        public Nullable<System.DateTime> dayCreate { get; set; }
        public string note { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<DSDatXe> DSDatXes { get; set; }
        public virtual ICollection<DSKSCanTT> DSKSCanTTs { get; set; }
        public virtual ICollection<DSTourCanTT> DSTourCanTTs { get; set; }
    }
}
