//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Taxi
    {
        public Taxi()
        {
            this.DSDatXes = new HashSet<DSDatXe>();
        }
    
        public string bienSo { get; set; }
        public string maDD { get; set; }
        public Nullable<int> soGhe { get; set; }
        public string phoneNum { get; set; }
        public string note { get; set; }
    
        public virtual ICollection<DSDatXe> DSDatXes { get; set; }
        public virtual TourDestination TourDestination { get; set; }
    }
}
