//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TourDestination
    {
        public TourDestination()
        {
            this.Blogs = new HashSet<Blog>();
            this.HomeStays = new HashSet<HomeStay>();
            this.Taxis = new HashSet<Taxi>();
            this.Trips = new HashSet<Trip>();
            this.Trips1 = new HashSet<Trip>();
        }
    
        public string maDD { get; set; }
        public string maTinh { get; set; }
        public string tenDD { get; set; }
        public string pic { get; set; }
        public string note { get; set; }
    
        public virtual ICollection<Blog> Blogs { get; set; }
        public virtual ICollection<HomeStay> HomeStays { get; set; }
        public virtual Province Province { get; set; }
        public virtual ICollection<Taxi> Taxis { get; set; }
        public virtual ICollection<Trip> Trips { get; set; }
        public virtual ICollection<Trip> Trips1 { get; set; }
    }
}
