//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSDatXe
    {
        public string maHD { get; set; }
        public string bienSo { get; set; }
        public Nullable<double> cost { get; set; }
        public string note { get; set; }
    
        public virtual ElecBill ElecBill { get; set; }
        public virtual Taxi Taxi { get; set; }
    }
}
