//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HomeStay
    {
        public HomeStay()
        {
            this.DSKSCanTTs = new HashSet<DSKSCanTT>();
            this.DSKSTheoTrips = new HashSet<DSKSTheoTrip>();
            this.DSKSTrongWLs = new HashSet<DSKSTrongWL>();
        }
    
        public string maKS { get; set; }
        public string maDD { get; set; }
        public string tenKS { get; set; }
        public string phoneNum { get; set; }
        public string pic { get; set; }
        public string note { get; set; }
    
        public virtual ICollection<DSKSCanTT> DSKSCanTTs { get; set; }
        public virtual ICollection<DSKSTheoTrip> DSKSTheoTrips { get; set; }
        public virtual ICollection<DSKSTrongWL> DSKSTrongWLs { get; set; }
        public virtual TourDestination TourDestination { get; set; }
    }
}
