//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nation
    {
        public Nation()
        {
            this.Provinces = new HashSet<Province>();
        }
    
        public string maQG { get; set; }
        public string tenQG { get; set; }
        public string pic { get; set; }
        public string note { get; set; }
    
        public virtual ICollection<Province> Provinces { get; set; }
    }
}
